import {test,expect} from '@playwright/test';
import crypto from 'node:crypto';
test('real browser → proxy → API → PostgreSQL → worker: full journey and deletion',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await page.getByRole('button',{name:'로그인',exact:true}).click();
  await page.getByRole('button',{name:'초대 코드로 가입'}).click();
  await page.getByLabel('이메일',{exact:true}).fill(`e2e-${Date.now()}@example.invalid`);
  await page.locator('#auth-form [name=password]').fill('synthetic-test-password-2026');
  await page.getByLabel('팀 초대 코드').fill('synthetic-e2e-invite');
  await page.getByRole('button',{name:'가입하기',exact:true}).click();
  await expect(page.getByRole('heading',{name:'이야기 전에 확인해 주세요'})).toBeVisible();
  await page.locator('[name=service_processing]').check();await page.locator('[name=sensitive_processing]').check();
  await page.locator('[name=history_storage]').check();await page.locator('[name=cross_session_memory]').check();
  await page.getByRole('button',{name:'동의하고 계속'}).click();await page.getByRole('button',{name:'새 이야기 시작'}).click();
  await page.getByLabel('이야기 제목').fill('연동 검증');await page.getByRole('button',{name:'이야기 시작',exact:true}).click();
  await page.locator('#answer-form textarea').fill('친구');await page.getByRole('button',{name:'답변 보내기',exact:true}).click();
  await page.locator('input[name=relation][value=friend]').check();await page.locator('input[name=contact_frequency][value=weekly]').check();
  await page.getByRole('button',{name:'답변 보내기',exact:true}).click();
  await page.reload();await expect(page.getByRole('heading',{name:'친구의 이야기'})).toBeVisible();
  await expect(page.locator('.history')).toContainText('친구');
  await page.locator('input[name=options][value=low_mood]').check();await page.getByRole('button',{name:'답변 보내기',exact:true}).click();
  await page.getByRole('button',{name:'말하는 방법 정리하기'}).click();
  await expect(page.getByRole('heading',{name:'이렇게 말을 건네 보세요'})).toBeVisible({timeout:30000});
  await page.screenshot({path:'artifacts/desktop-guidance.png',fullPage:true});
  await page.getByRole('button',{name:'이 행동을 계획으로 선택'}).click();
  await expect(page.getByRole('heading',{name:'내가 선택한 작은 행동'})).toBeVisible();
  await page.reload();await expect(page.getByRole('heading',{name:'이렇게 말을 건네 보세요'})).toBeVisible();
  await page.getByRole('button',{name:'해 본 이야기 남기기'}).click();
  await page.getByRole('button',{name:'경험 저장'}).click();await expect(page.locator('#dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'기억 확인하기'}).click();await expect(page.locator('#dialog')).toContainText('선택으로 확인');
  await page.locator('#dialog').getByRole('button',{name:'닫기',exact:true}).click();
  await page.getByRole('button',{name:'내 기록',exact:true}).click();
  page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'삭제',exact:true}).click();
  await expect(page.getByRole('heading',{name:'첫 이야기를 함께 시작해 볼까요?'})).toBeVisible();
  await page.getByRole('button',{name:'내 설정'}).click();await page.getByRole('button',{name:'계정과 모든 기록 삭제'}).click();
  await page.locator('#delete-account-form [name=password]').fill('synthetic-test-password-2026');await page.locator('#delete-account-form input[type=checkbox]').check();
  await page.getByRole('button',{name:'모든 기록 삭제',exact:true}).click();await expect(page.getByRole('button',{name:'로그인',exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});
test('one-click demo opens a private temporary conversation without registration',async({page,browser})=>{
  await page.goto('/');
  await page.getByRole('button',{name:'가입 없이 체험하기'}).click();
  await expect(page.getByRole('heading',{name:'친구의 이야기'})).toBeVisible();
  await expect(page.locator('#answer-form')).toBeVisible();
  const capabilities=await (await page.request.get('/api/v2/capabilities')).json();
  if(!capabilities.model_execution_enabled){
    await page.getByRole('button',{name:'가이드 화면 예시 보기'}).click();
    await expect(page.locator('#dialog')).toContainText('AI 생성 결과 아님');
    await expect(page.locator('#dialog')).toContainText('입력한 답변을 분석하거나 개인화하지 않았습니다.');
    await page.locator('#dialog').getByRole('button',{name:'닫기',exact:true}).click();
  }
  const me=await (await page.request.get('/api/auth/me')).json();
  expect(me.user.is_demo).toBe(true);
  const projects=await (await page.request.get('/api/v2/projects')).json();
  expect(projects.projects).toHaveLength(1);
  expect(projects.projects[0].temporary).toBe(true);
  const separate=await browser.newContext();
  try{expect((await separate.request.get('/api/v2/projects')).status()).toBe(401);}finally{await separate.close();}
  await page.reload();
  await expect(page.getByRole('heading',{name:'친구의 이야기'})).toBeVisible();
  await page.getByRole('button',{name:'내 설정'}).click();
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'지금 시연 기록 삭제'}).click();
  await expect(page.getByRole('button',{name:'가입 없이 체험하기'})).toBeVisible();
  expect((await page.request.get('/api/auth/me')).status()).toBe(401);
});
test('ambiguous transport retry, correction, safety resume and consent withdrawal use persisted state',async({page})=>{
  const origin='http://localhost:18080',headers={Origin:origin};
  const registration=await page.request.post('/api/auth/register',{headers,data:{email:`resilience-${Date.now()}@example.invalid`,password:'synthetic-test-password-2026',invite_code:'synthetic-e2e-invite'}});
  expect(registration.status()).toBe(201);
  const consent=await page.request.post('/api/v2/consents',{headers,data:{request_id:crypto.randomUUID(),version:'malssi-consent-v1',purposes:{service_processing:true,sensitive_processing:true,history_storage:true,cross_session_memory:false}}});expect(consent.status()).toBe(201);
  const p=await (await page.request.post('/api/v2/projects',{headers,data:{request_id:crypto.randomUUID(),title:'복구 검증'}})).json();
  const c=await (await page.request.post(`/api/v2/projects/${p.project_id}/conversations`,{headers,data:{request_id:crypto.randomUUID(),goal:'understand'}})).json();
  await page.goto('/#conversation='+c.conversation_id);
  let firstBody;
  await page.route('**/api/v2/conversations/*/turns',async route=>{firstBody=route.request().postDataJSON();await route.fetch();await route.abort('failed');await page.unroute('**/api/v2/conversations/*/turns');},{times:1});
  await page.locator('#answer-form textarea').fill('합성친구');await page.getByRole('button',{name:'답변 보내기',exact:true}).click();
  await expect(page.getByRole('button',{name:'같은 요청 다시 보내기'})).toBeVisible();
  const retried=page.waitForRequest(r=>r.url().endsWith('/turns'));
  await page.getByRole('button',{name:'같은 요청 다시 보내기'}).click();expect((await retried).postDataJSON()).toEqual(firstBody);
  await expect(page.locator('.history .history-item')).toHaveCount(1);
  await page.getByRole('button',{name:'답변 정정',exact:true}).click();await page.locator('#dialog textarea[name=text]').fill('벗');
  await page.locator('#dialog').getByRole('button',{name:'답변 보내기',exact:true}).click();await expect(page.getByRole('heading',{name:'벗의 이야기'})).toBeVisible();
  await page.getByText('자유롭게 이야기 추가하기',{exact:true}).click();await page.locator('#message-form textarea').fill('친구가 지금 자해하고 있어요');
  await page.getByRole('button',{name:'이야기 보내기',exact:true}).click();await expect(page.getByRole('heading',{name:'먼저 지금의 안전을 확인해 주세요'})).toBeVisible();
  await page.reload();await expect(page.getByRole('heading',{name:'먼저 지금의 안전을 확인해 주세요'})).toBeVisible();
  await expect(page.getByRole('button',{name:'말하는 방법 정리하기'})).toHaveCount(0);
  await page.locator('#safety-form textarea').fill('현재 즉각적인 위험은 없고 안전한 곳에 있어요.');await page.locator('#safety-form [name=resume]').check();
  await page.getByRole('button',{name:'안전 상황 전달'}).click();await expect(page.getByRole('heading',{name:'먼저 지금의 안전을 확인해 주세요'})).toHaveCount(0);
  await page.getByRole('button',{name:'내 설정'}).click();await page.locator('[name=history_storage]').uncheck();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'동의 설정 저장'}).click();
  await expect(page.getByRole('heading',{name:'첫 이야기를 함께 시작해 볼까요?'})).toBeVisible();
  expect((await page.request.get('/api/v2/conversations/'+c.conversation_id)).status()).toBe(404);
  await page.request.delete('/api/v2/account',{headers,data:{request_id:crypto.randomUUID(),current_password:'synthetic-test-password-2026'}});
});
test('mobile layout and help remain usable without signing in',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.getByRole('button',{name:'안전 도움'}).click();await expect(page.getByRole('heading',{name:'지금 안전이 먼저라면'})).toBeVisible();
  await page.locator('#dialog').getByRole('button',{name:'닫기',exact:true}).click();
  await page.screenshot({path:'artifacts/mobile-home.png',fullPage:true});
});
