import { randomBytes } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const args=process.argv.slice(2);
const arg=(name,fallback)=>{const i=args.indexOf(name);return i<0?fallback:args[i+1];};
const origin=arg('--origin','http://localhost:8080'),url=new URL(origin);
if(url.origin!==origin||!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error('Use an exact HTTP(S) origin');
if(url.protocol==='https:'&&url.port)throw new Error('Automatic HTTPS setup uses port 443. Configure nonstandard TLS ports manually.');
if(url.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(url.hostname))throw new Error('Remote browser access requires HTTPS; HTTP setup is for loopback development.');
const mode=arg('--mode','internal');
if(!['internal','release'].includes(mode))throw new Error('--mode must be internal or release');
const modelUrl=arg('--model-url',''),model=modelUrl?arg('--model',''):'';
if(modelUrl&&!model)throw new Error('--model-url requires --model');
const modelOrigin=modelUrl?new URL(modelUrl).origin:'';
const secret=()=>randomBytes(32).toString('hex');
const values={COMPOSE_PROJECT_NAME:'malssi',COMPOSE_PROFILES:modelUrl?'model':'',HOP_PUBLIC_ORIGIN:origin,HOP_SITE_ADDRESS:url.protocol==='https:'?url.host:':80',HOP_HTTP_BIND:url.protocol==='https:'?'0.0.0.0':'127.0.0.1',HOP_HTTP_PORT:url.protocol==='https:'?'80':url.port||'80',HOP_HTTPS_PORT:url.protocol==='https:'?'443':'8443',HOP_COOKIE_SECURE:String(url.protocol==='https:'),HOP_DB_ADMIN_PASSWORD:secret(),HOP_DB_MIGRATOR_PASSWORD:secret(),HOP_DB_APP_PASSWORD:secret(),HOP_CONTENT_KEY:randomBytes(32).toString('base64'),HOP_INVITE_CODE:secret(),HOP_ALLOW_REGISTRATION:'true',HOP_DEMO_ENABLED:String(mode==='internal'),HOP_V2_ALLOW_DRAFT:String(mode==='internal'),HOP_V2_MODEL_ENABLED:String(Boolean(modelUrl)),HOP_LLM_BASE_URL:modelUrl||'http://host.docker.internal:18011/v1',HOP_LLM_MODEL:model||'configure-your-local-model',HOP_LLM_API_KEY:'',HOP_MODEL_ALLOWED_ORIGINS:modelOrigin,HOP_MODEL_CONTEXT_SIZE:'16384'};
for(const value of Object.values(values))if(/[\r\n'\\]/.test(value))throw new Error('Unsupported environment value');
const body=Object.entries(values).map(([k,v])=>`${k}='${v}'`).join('\n')+'\n';
await writeFile(fileURLToPath(new URL('../.env',import.meta.url)),body,{flag:'wx',mode:0o600});
console.log(`Created .env without printing secrets. Mode: ${mode}. Origin: ${origin}.`);
console.log('The invite code is stored in .env. Preserve HOP_CONTENT_KEY with database backups.');
